config/routes.rb
Rails.application.routes.draw do

  resources :owners

  resources :flats do
    collection do
      get 'top' => "flats#top"
    end
    member do
      get 'owner' => "flats#owner"
    end
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :flats, only: [:index]
  end

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  # belongs_to :owner
  has_many :reviews, dependent: :destroy
  validates :stars, inclusion: { in: [1,2,3], allow_nil: false }
  validates :title, uniqueness: true, presence: true
  validates :address, presence: true

   geocoded_by :address
   after_validation :geocode, if: :address_changed?
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :flats
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/flats_controller.rb
class Admin::FlatsController < ApplicationController
  def index
    # Let's anticipate on next week (with login)
    @flats = current_user.flat
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy, :owner]

  # GET /flats
  # GET /flats.json
  def index
    # @flats = Flat.all
    @flats = Flat.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
    @flat_coordinates = { lat: @flat.latitude, lng: @flat.longitude }
  end

  def owner

  end

  def top
    @flats = Flat.where(stars: 3)
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat
      else
      render :new
    # respond_to do |format|
    #   if @flat.save
    #     format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
    #     format.json { render :show, status: :created, location: @flat }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @flat.errors, status: :unprocessable_entity }
    #   end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    if @flat.update(flat_params)
      redirect_to @flat
    else
      render :edit
    end
    # respond_to do |format|
    #   if @flat.update(flat_params)
    #     format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @flat }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @flat.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:title, :address, :description, :stars, :user_id, :latitude, :longitude)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_flat, only: [ :new, :create ]

  def new
    @review = Review.new
  end

  def create
    @review = @flat.reviews.build(review_params)
    @review.save
    redirect_to flat_path(@flat)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
  def find_flat
    @flat = Flat.find(params[:flat_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/flats/index.html.erb
<h1>My list of flats</h1>
<% @flats.each do |flat| %>
  <h2><%= flat.title %></h2>
  <p><%= flat.address %></p>
<% end %>

app/views/flats/_flat.html.erb
<div class="card" style="background-image: url(<%= image_path 'card-paris.jpg'%>);">
  <div class="card-header">

  </div>
  <div class="card-body">
    <h2><%= flat.title %></h2>
    <p class="address"><%= flat.address %></p>
    <p><%= flat.description %></p>
    <%= link_to 'Show', flat %>
    <%= link_to 'Edit', edit_flat_path(flat) %>
    <%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <% if @flat.errors.any? %>
   <div id="error_explanation">
    <ul>
      <%@flat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
   </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :stars %>
    <%= f.input :address %>
    <%= f.input :description %>


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flats</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="form-inline">
        <%= simple_form_for :search, url: flats_path, method: :get, remote: true do |f| %>
        <%= f.input :address, placeholder: 'Where do you want to try ?', label: false %>
        <%= f.input :date, as: :date, label: false%>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      </div>
    </div>
  </div>
</div>
<div id="map" style="width: 100%; height: 600px;"></div>
  <% content_for(:after_js) do %>
    <script >
      $(document).ready(function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
        });
      });
    </script>
  <% end %>

 <!-- <table>


  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.title %></td>
        <td><%= flat.address %></td>
        <td><%= flat.description %></td>
        <td><%= flat.stars %></td>
        <td><%= flat.user_id %></td>
        <td><%= flat.latitude %></td>
        <td><%= flat.longitude %></td>
        <td><%= link_to 'Show', flat %></td>
        <td><%= link_to 'Edit', edit_flat_path(flat) %></td>
        <td><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->
<div class="col-sm-4">
  <% @flats.each do |f| %>
  <%= render "flat", flat: f %>
  <% end %>
</div>
<br>
<%= link_to 'New Flat', new_flat_path %>

app/views/flats/new.html.erb
<h1>New Flat</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= render 'form', flat: @flat %>

      <%= link_to 'Back', flats_path %>
    </div>
  </div>
</div>

app/views/flats/owner.html.erb
<h1>owner of this flat <%= @flat.title%></h1>
<h2><%= @flat.owner %></h2>


<%= link_to 'Back to Flats', flat_path(@flat) %>

app/views/flats/show.html.erb
<% content_for(:title) do %>
  <%= @flat.title %> is on AIRBNB-CLONE
<% end %>
<% content_for(:description) do %>
  <%= @flat.description %> is one the best flat
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @flat.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @flat.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flat.description %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @flat.stars %>
</p>

<p>
  <strong>User:</strong>
  <%= @flat.user_id %>
</p>

<!-- <p>
  <strong>Latitude:</strong>
  <%= @flat.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @flat.longitude %>
</p> -->

<ul>
  <% @flat.reviews.each do |review| %>
  <li><%= review.content %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %> |
<%= link_to 'info about owner', owner_flat_path(@flat) %>|
<%= link_to 'Add review', new_flat_review_path(@flat) %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var coord = <%= raw @flat_coordinates.to_json %>;
      alert('Flat coordinates are ' + coord.lat + ', ' + coord.lng);
    });
  <% end %>
<% end %>

app/views/flats/top.html.erb
<h1>Top Flats</h1>

<ul>
  <% @flats.each do |flat| %>
  <li><%= flat.title %></li>

  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield(:title).blank? ? "AIRBNB-CLONE" : yield(:title) %></title>

    <meta name="description" content="<%= (yield(:description) || "").squish %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>


  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>

    <%= yield(:after_js) %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= simple_form_for(@owner) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owners</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.user_id %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @owner.user_id %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/pages/_card.html.erb
<div class="col-xs-12 col-sm-4">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= flat.photo %>');">
  <div class="card-category"><%= flat.user.first_name%></div>

    <div class="card-description">
      <h2><%= flat.title %> </h2>
      <p><%= flat.description[0..50] %></p>
    </div>
    <%= image_tag flat.user.avatar, class:"card-user avatar-large" %>
    <%= link_to '', flat, class: "card-link" %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<div class="banner" style="background-image: url(<%= image_path 'background.jpg' %>);">
  <div class="banner-content">
    <h1>Some Stuff</h1>
    <p>Very cool stuff, useful and smart</p>
    <a class="btn btn-primary btn-lg">GET IT</a>
    <%= link_to 'FLATS', flats_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>



    <div class=" text-center padded features">
      <div class= "cantainer">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-3">

          <%= image_tag 'globe.png' %>
          <h2>Discover the world</h2>
          <p>The earth is your new home.</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">

          <%= image_tag 'dollar.png' %>
          <h2>Pay online</h2>
          <p>No cash issues anymore.</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">

          <%= image_tag 'beer.png' %>
          <h2>Meet people</h2>
          <p>Discover new culture and lifestyle.</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">

          <%= image_tag 'heart.png' %>
          <h2>Share and love</h2>
          <p>Join a community you will love.</p>
        </div>
      </div>
      </div>
    </div>
    <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: url(<%= image_path 'card-paris.jpg'%>);">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>

  <%= image_tag 'seb.jpg', class: 'card-user avatar' %>
  <a class="card-link" href="#" ></a>
</div>

    </div>
    <div class="col-xs-12 col-sm-4">

      <div class="card" style="background-image: url(<%= image_path 'card-london.jpeg'%>);">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>

  <%= image_tag 'romain.jpeg', class: 'card-user avatar' %>
  <a class="card-link" href="#" ></a>
</div>

    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: url(<%= image_path 'card-brussels.jpeg'%>);">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
    <%= image_tag 'anne.jpg', class: 'card-user avatar' %>
  <a class="card-link" href="#" ></a>
</div>
    </div>
  </div>
</div>
    <div class="text-center padded" id="newsletter">
      <h2>Get news from us</h2>
      <p>Leave us your mail and get news from us</p>
      <form class="form-inline">
        <input placeholder="bob@gmail.com" class="form-control" type="email">
        <input value="Subscribe" class="btn btn-primary btn-bordered btn-bordered-primary" type="submit">
      </form>
    </div>

  <div id="map" style="width: 100%; height: 400px;"></div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<script type="text/javascript">
var myLatlng = new google.maps.LatLng(48.8655909, 2.378983);

var myOptions = {
  zoom: 16,
  center: myLatlng,
  scrollwheel: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP,
  styles: [] // TODO: replace [] by array from https://snazzymaps.com/
};

var map = new google.maps.Map(document.getElementById('map'), myOptions);
var marker = new google.maps.Marker({
  position: myLatlng,
  map: map,
  title: "You are here!"
});
</script>

    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  <div id="footer">
    <ul class="list-inline">
      <li><a href=""><i class="fa fa-youtube"></i></a></li>
      <li><a href=""><i class="fa fa-instagram"></i></a></li>
      <li><a href=""><i class="fa fa-facebook"></i></a></li>
      <li><a href=""><i class="fa fa-twitter"></i></a></li>
    </ul>
    <p>This is a Airbnb Clone</p>
  </div>
  </body>
</html>

app/views/reviews/new.html.erb
<h1>add review for <%= @flat.title %></h1>


<%= simple_form_for [@flat, @review] do |f| %>

  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>